### ISSUE TITLE
Issue in relayFeedbackTest(measuredValue)

### ISSUE THREAD

**Issue by msavasci** [hj91/autotuner-pi-controller#1]
The `relayState` is initialized as 1. If `measuredValue` is a positive value, then the if condition on line 76 will never work, so `relayState` will never be switched to -1 (line 91). As a result, relayFeedbackTest will not work at all.

**Comment by hj91** [comment]
Correct - it should be modified as 

 this.relayState = (initialMeasuredValue >= 0) ? -1 : 1;

Thank you for pointing it out.

**Comment by hj91** [comment]
Updated the relayState logic - now closing this issue
